apiVersion: v1
kind: Pod
metadata:
  name: <pod-name>
spec:
  containers:
  - name: <container-name>
    image: <container-image>
    volumeMounts:
    - mountPath: /path/on/container
      name: <volume-name>
  volumes:
  - name: <volume-name>
    hostPath:
      # directory location on host node
      path: /path/to/local/dir
      type: Directory
      # hostPath volume will point to the local volume on the cluster node
      # Not the actual host
      # e.g if we create a minikube cluster with 3 nodes, 
      # the local volume to which this points localted on the node
      # the pod is scheduled to run. In case the pod gets scheduled 
      # on some other node, the volume will not exist on that node
      # so data will not persist