apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patches:
- target:
    version: v1
    kind: ServiceAccount
    name: mysql-operator-sa
  path: <patch-file-path>
    