apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
helmCharts:
- name: mysql-operator
  releaseName: p10y-mysql-operator
  version: 2.0.7
  repo: https://mysql.github.io/mysql-operator/