# LoadBalancer for a pod of statefulset
# 
## [Link](https://stackoverflow.com/questions/58668190/how-to-set-hostname-for-kubernetes-pod-in-statefulset)
# 
apiVersion: v1
kind: Service
metadata:
  name: <service-name>
spec:
  type: LoadBalancer
  selector:
    statefulset.kubernetes.io/pod-name: <stateful-set pod-name>
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

